### ISSUE TITLE
Does not kill wineserver after closing

### ISSUE THREAD

**Issue by Renen12** [vinegarhq/vinegar#173]
Vinegar does not kill wineserver after closing, and when you launch the roblox app from the terminal it complains with the error:
034c:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.
2023/09/25 16:42:10 binary.go:158: exit status 1

**Comment by apprehensions** [comment]
Flatpak?

**Comment by Thelolguy1** [comment]
You have to wait a moment before it kills properly. This error happens when you click play immediately after closing.

**Comment by Renen12** [comment]
> Flatpak?

yes

**Comment by Renen12** [comment]
@Thelolguy1 when I run it from the terminal and close it it just hangs, and doesn't kill wineserver.

**Comment by Renen12** [comment]
@apprehensions Yes.

**Comment by robertxgray** [comment]
Same problem here. I'm using this script to run the game as a workaround.

```bash
#!/bin/sh
(
	sleep 10
	echo "Waiting for game exit"
	while pgrep RobloxPlayerBet
	do
		sleep 5
	done
	echo "Killing Vinegar"
	pkill -s 0 -9 bwrap
) &

flatpak run io.github.vinegarhq.Vinegar player
```

**Comment by apprehensions** [comment]
Vinegar automatically kills wine after RobloxPlayerBeta exits... What is the point of your script?

Its better to use `flatpak kill io.github.vinegarhq.Vinegar` rather than abruptly killing the sandbox.

**Comment by robertxgray** [comment]
> Vinegar automatically kills wine after RobloxPlayerBeta exits... What is the point of your script?

It doesn't work for me. If I run the game from a terminal, Vinegar keeps running after the game window is closed. Only after pressing Ctrl-C, the message "Killing wineserver" is shown and I get the prompt back.

> Its better to use `flatpak kill io.github.vinegarhq.Vinegar` rather than abruptly killing the sandbox.

Thanks. I've updated the script.

**Comment by apprehensions** [comment]
Interesting.. Roblox, if still running without a window still has a process. Meaning that its still running and hence your script shouldn't be able to kill its still running. I can't personally reproduce this issue myself, as player never hanged for me.

**Comment by Thelolguy1** [comment]
Can't reproduce the bug myself either.

**Comment by NeryK** [comment]
I have the issue too, running the Flatpak from a desktop shortcut on a Steam Deck in desktop mode.
When I close the game window, the application does not quit but continues to run in the background.

**Comment by Renen12** [comment]
I switched to nixOS yesterday, and now the bug is gone for me.

**Comment by TheAnnoyingFruit** [comment]
Experiencing the same issue of opensuse tumbleweed with the flatpak

**Comment by MentoskaPraha** [comment]
I'm experiencing the same issue on Arch with the Flatpak. The annoying part is that you can't start another instance of Roblox or Roblox Studio until you kill the running process.

**Comment by Renen12** [comment]
I switched to nixOS a few days ago, and now the bug is gone

**Comment by Thelolguy1** [comment]
Seems to be a bug with the Roblox executable, not vinegar. I can't personally reproduce the issue.

**Comment by TheAnnoyingFruit** [comment]
I had this on opensuse tumbleweed and now also experience this on fedora

**Comment by apprehensions** [comment]
Fixed with 5deb2e8810e5208a000a0b017af7ddb1c3ef444b

**Comment by TheAnnoyingFruit** [comment]
> Fixed with [5deb2e8](https://github.com/vinegarhq/vinegar/commit/5deb2e8810e5208a000a0b017af7ddb1c3ef444b)

The flatpak was very recently updated to 1.5.2 and this issue is still present there

**Comment by apprehensions** [comment]
How?

**Comment by TheAnnoyingFruit** [comment]
> How?
This seems to only be relevant to me using fedora silverblue. On a regular non-immutable fedora it is fixed. Currently troubleshooting, unsure what the immutable base vs stock fedora difference has to do with this issue.

**Comment by TheAnnoyingFruit** [comment]
It does not seem to be related to silverblue or regular fedora. It seems to be related to the renderer being used. I experience this when using vulkan but when I switch to opengl this problem no longer occurs

**Comment by TheAnnoyingFruit** [comment]
Hopefully this can be useful to you @apprehensions as it isn't to me. ^

**Comment by NeryK** [comment]
Not fixed on Steam Deck either, with flatpak 1.5.3 unfortunately.

> Seems to be a bug with the Roblox executable, not vinegar. I can't personally reproduce the issue to the severity mentioned in this thread.

This seems to be the crux of the issue. The RobloxPlayerBeta process does not end when closing the window. On Steam Deck its systematic, not a random phenomenon. As soon as the RobloxPlayerBeta process is killed manually, vinegar stops properly.

**Comment by apprehensions** [comment]
do we really have to add roblox window polling

**Comment by apprehensions** [comment]
Can anyone here provide their roblox log when this bug occurs? Does Roblox's process still run after it's window closes?

**Comment by TheAnnoyingFruit** [comment]
[0.598.0.5980624_20231020T152141Z_Player_F948C_last.log](https://github.com/vinegarhq/vinegar/files/13055841/0.598.0.5980624_20231020T152141Z_Player_F948C_last.log)
The process still runs after the window closes and I can hear the game audio. I end the task in gnome system monitor to fully close it.

**Comment by apprehensions** [comment]
Your Log:
```
2023-10-20T15:21:47.463Z,6.463007,0168,6 [FLog::WindowsLuaApp] Application did receive notification, type(NATIVE_EXIT, 35), data()
2023-10-20T15:21:47.463Z,6.463007,0168,6 [FLog::WindowsLuaApp] Lua requested native exit.
2023-10-20T15:21:47.467Z,6.467028,011c,6 [FLog::Graphics] Vulkan: destroying window frame buffer
2023-10-20T15:21:47.757Z,6.757864,011c,12 [DFLog::HttpTraceError] HttpResponse(#553 00007F2DC655B570) time:99.8ms (net:99.6ms callback:0.0ms timeInRetryQueue:0.0ms) error:9 message:HttpError: Aborted url:{ "https://ecsv2.roblox.com/client/pbe" } ip: external:0 numberOfTimesRetried:0
2023-10-20T15:21:47.758Z,6.758865,011c,12 [DFLog::HttpTraceError] HttpResponse(#554 00007F2DC655B870) time:100.0ms (net:99.8ms callback:0.0ms timeInRetryQueue:0.0ms) error:9 message:HttpError: Aborted url:{ "https://ecsv2.roblox.com/client/pbe" } ip: external:0 numberOfTimesRetried:0
2023-10-20T15:21:47.858Z,6.858100,011c,12 [DFLog::HttpTraceError] HttpResponse(#555 00007F2DC655AF70) time:100.1ms (net:96.2ms callback:0.0ms timeInRetryQueue:0.0ms) error:9 message:HttpError: Aborted url:{ "https://client-telemetry.roblox.com" } ip: external:0 numberOfTimesRetried:0
2023-10-20T15:21:47.859Z,6.859097,011c,6 [FLog::SingleSurfaceApp] shutDown: (stage:UGCGame).
2023-10-20T15:21:47.859Z,6.859097,011c,6 [FLog::SurfaceController] SurfaceController[_:1]::pause dataModel(00007F2E9766E790), view(00007F2E031AC140), destroyView:1.
2023-10-20T15:21:47.859Z,6.859097,011c,6 [FLog::SurfaceController] drainRenderingJobs
2023-10-20T15:21:47.859Z,6.859097,011c,6 [FLog::SurfaceController] SurfaceController::RenderJob[_:1]::~RenderJob
2023-10-20T15:21:48.592Z,7.592612,0178,12 [DFLog::HttpTraceError] HttpResponse(#564 00007F2D72F98D50) time:99.7ms (net:99.5ms callback:0.0ms timeInRetryQueue:0.0ms) error:9 message:HttpError: Aborted url:{ "https://ecsv2.roblox.com/client/pbe" } ip: external:0 numberOfTimesRetried:0
```

What it should normally be like:
```
2023-10-20T16:07:41.595Z,5.595538,0114,6 [FLog::SingleSurfaceApp] shutDown: (stage:LuaApp).
0114:err:ole:CoUninitialize Mismatched CoUninitialize
2023-10-20T16:07:41.596Z,5.596538,0114,6 [FLog::SurfaceController] SurfaceController[_:1]::pause dataModel(000000000C870540), view(0000000015967510), destroyView:1.
2023-10-20T16:07:41.596Z,5.596538,0114,6 [FLog::SurfaceController] drainRenderingJobs
2023-10-20T16:07:41.596Z,5.596538,0114,6 [FLog::SurfaceController] SurfaceController::RenderJob[_:1]::~RenderJob
2023-10-20T16:07:41.604Z,5.604536,0114,6 [FLog::SurfaceController] stop
2023-10-20T16:07:41.604Z,5.604536,0114,6 [FLog::SurfaceController] drainRenderingJobs
2023-10-20T16:07:41.604Z,5.604536,0114,6 [FLog::SingleSurfaceApp] destroyLuaApp: (stage:LuaApp) blocking:true.
2023-10-20T16:07:41.669Z,5.669882,0114,6 [FLog::Output] Closing Fmod (as 0, ml 0, sl 0).
2023-10-20T16:07:41.698Z,5.698160,0114,6 [FLog::Output] Fmod Closed.
2023-10-20T16:07:41.709Z,5.709270,0114,6 [FLog::SingleSurfaceApp] destroyLuaApp: (stage:LuaApp)... finished destroying luaApp.
2023-10-20T16:07:41.709Z,5.709270,0114,6 [FLog::SingleSurfaceApp] setStage: (stage:None)
2023-10-20T16:07:41.709Z,5.709270,0114,6 [FLog::SingleSurfaceApp] destroy controllers
2023-10-20T16:07:41.709Z,5.709270,0114,6 [FLog::SurfaceController] SurfaceController[_:1]::~SurfaceController, count: 0
2023-10-20T16:07:41.709Z,5.709270,0114,6 [FLog::SingleSurfaceApp] setStage: (stage:Native)
0114:fixme:wininet:InternetSetOptionW Option INTERNET_OPTION_END_BROWSER_SESSION: semi-stub
2023-10-20T16:07:41.709Z,5.709270,0114,6 [FLog::LogWin32BTId] LogWin32BTId, App, internal browser session end
2023-10-20T16:07:41.709Z,5.709270,0114,6 [FLog::SingleSurfaceApp] unregisterMemoryPrioritizationCallback
```

So it seems to me this is a fault of Roblox itself. Try using a differerent renderer.

I will implement a wineserver kill  (#221) with the line `shutDown: (stage:` if that doesnt work.

**Comment by TheAnnoyingFruit** [comment]
Well I did previously state that it does seem to be related to renderer because this happens on vulkan but not with opengl. Vulkan tends to run better for me though so I usually try to stick with that.

**Comment by apprehensions** [comment]
Has the shutDown check in parsing log solved the problem?

**Comment by TheAnnoyingFruit** [comment]
Where should I be putting that line to test?

**Comment by apprehensions** [comment]
No, Has the latest commits solved this problem, which handle the log?

**Comment by TheAnnoyingFruit** [comment]
Sorry If I'm not understanding I'm not the most knowledgeable at this stuff. From my understanding you mean I should build this from source to test the latest commits. If so I frankly have been having a hell of a time getting vinegar to work on fedora when building from source. Aside from all the dependency issues I had to build it, I can't even getting roblox to launch after the fact.

**Comment by TheAnnoyingFruit** [comment]
Finally got it. From what I have seen yes, the problem appears to be solved. When I close the roblox client that is using vulkan it fully closes and no tasks are remaining running in the background.

**Comment by TheAnnoyingFruit** [comment]
Sorry for being such a bother but this issue was rather annoying. @apprehensions You have been EXTREMELY helpful and I appreciate all the help

**Comment by apprehensions** [comment]
If you could, it would be great if you could hop on the discord server, as i want to see if removing that shutdown detector partially solves the problem.

**Comment by TheAnnoyingFruit** [comment]
Ok I'm there my name is the same

**Comment by NeryK** [comment]
Confirmed fixed on Steam Deck too, with flatpak 1.5.4.
Much appreciated, thanks.
