### ISSUE TITLE
Vinegar crashes after logging in once per install

### ISSUE THREAD

**Issue by businessfish** [vinegarhq/vinegar#222]
Logging in once on a fresh install of the vinegar flatpak works as expected, but upon closing the game any future attempts to launch vinegar will crash before the actual roblox window opens.

I've tested the following:

- Launching the roblox app through vinegar, logging in with quick log in, it works as normal, close roblox app, relaunch crashes
- Clicking on a game from the roblox website through my browser, game launches once, subsequent launches crash
- Log in through either of the above methods and  then log out before closing the app, subsequent launches crash
- Relaunching the roblox app does work as long as you don't log in, but obviously this is useless

At the moment I'm dealing with it by reinstalling the flatpak every time I want to launch the game, which is not exactly ideal but it does work: 
`flatpak uninstall --delete-data io.github.vinegarhq.Vinegar -y; flatpak install flathub io.github.vinegarhq.Vinegar -y`

Here's the log for when it crashes:
```
$ vinegar player
2023/10/19 15:28:46 config.go:53: Using default configuration
2023/10/19 15:28:46 logs.go:27: Logging to file: /home/fish/.var/app/io.github.vinegarhq.Vinegar/cache/vinegar/logs/player-2023-10-19T15:28:46-04:00.log
2023/10/19 15:28:46 version.go:74: Fetching latest version of WindowsPlayer for channel live (https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/)
2023/10/19 15:28:47 version.go:94: Fetched WindowsPlayer canonical version 0.598.0.5980624
2023/10/19 15:28:47 version.go:55: Found WindowsPlayer version version-57e2dd886e0e42a5
2023/10/19 15:28:47 binary.go:137: WindowsPlayer is up to date (version-57e2dd886e0e42a5)
2023/10/19 15:28:47 fflags.go:88: Using renderer: D3D11
2023/10/19 15:28:47 fflags.go:33: Applying custom FFlags
2023/10/19 15:28:47 fflags.go:51: FFlags used: {
  "DFIntTaskSchedulerTargetFps": 640,
  "FFlagDebugGraphicsDisableD3D11": false,
  "FFlagDebugGraphicsDisableD3D11FL10": true,
  "FFlagDebugGraphicsDisableOpenGL": true,
  "FFlagDebugGraphicsDisableVulkan": true,
  "FFlagDebugGraphicsPreferD3D11": true,
  "FFlagDebugGraphicsPreferD3D11FL10": false,
  "FFlagDebugGraphicsPreferOpenGL": false,
  "FFlagDebugGraphicsPreferVulkan": false
}
2023/10/19 15:28:47 dxvk.go:20: Enabling DXVK DLL overrides
2023/10/19 15:28:47 binary.go:66: Launching WindowsPlayer
2023/10/19 15:28:47 exec.go:24: Starting command: /app/bin/wine /home/fish/.var/app/io.github.vinegarhq.Vinegar/data/vinegar/prefix/vinegar/versions/version-57e2dd886e0e42a5/RobloxPlayerBeta.exe
002c:fixme:winediag:loader_init wine-staging 8.18 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0080:fixme:xrandr:xrandr10_get_current_mode Non-primary adapters are unsupported.
0080:fixme:xrandr:xrandr10_get_current_mode Non-primary adapters are unsupported.
0080:fixme:xrandr:xrandr10_get_current_mode Non-primary adapters are unsupported.
0080:fixme:xrandr:xrandr10_get_current_mode Non-primary adapters are unsupported.
0080:fixme:xrandr:xrandr10_get_current_mode Non-primary adapters are unsupported.
0080:fixme:xrandr:xrandr10_get_current_mode Non-primary adapters are unsupported.
2023/10/19 15:28:49 binary.go:87: Waiting for Roblox's process to die :)
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0088:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0088:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0088:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0034:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
002c:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0024:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
2023/10/19 15:28:50 prefix.go:28: Killing wineprefix
2023/10/19 15:28:50 exec.go:30: Running command: /app/bin/wineserver -k
```

**Comment by Jokeronomy** [comment]
I'm also experiencing this issue with the same error. The suggested workaround didn't work for me (at all, it crashed under every circumstance) but this workaround did:
`flatpak run io.github.vinegarhq.Vinegar edit`
and then added the below lines to the config file:
```
[player]
forced_version="version-57e2dd886e0e42a5"

**Comment by apprehensions** [comment]
Should be fixed with recent versions of Roblox

**Comment by CODJointOps** [comment]
> Should be fixed with recent versions of Roblox

Still get the same crash on the latest version.

> [player]
> forced_version="version-57e2dd886e0e42a5"

Trying to download the older version now returns 403 Forbidden

**Comment by Florennum** [comment]
could someone give me that version because it gives me forbidden
