### ISSUE TITLE
"player: dxvk is only valid with d3d renderers" Error on Newest Commit d528dbc1b6cd4d6551efb7b4867aca2e504c8ed3

### ISSUE THREAD

**Issue by Countern** [vinegarhq/vinegar#254]
The error happens despite putting `dxvk = false` and `renderer = "Vulkan"` in `[global]` with the recent commit d528dbc1b6cd4d6551efb7b4867aca2e504c8ed3. Putting `dxvk = false` in both `[player]` and `[studio]` resolves the error but I don't think that's really intuitive to do. The previous commit 9324a23ed650180fb9778f7c5beabfb27c475b4d (or v1.5.7) doesn't have this error

**Comment by RackYican** [comment]
same here, where do you change graphic config?

**Comment by Countern** [comment]
> same here, where do you change graphic config?

You can find it in `/home/USER/.config/vinegar/config.toml` or run the command `vinegar edit` (if on flatpak: `flatpak run io.github.vinegarhq.Vinegar edit`) to directly edit the config file within the terminal.

**Comment by Thelolguy1** [comment]
Noted, we are working on a fix

**Comment by raluvy95** [comment]
I'm having the same issue right after creating configuration (even emptys), at least on both stable and flatpak

**Comment by Thelolguy1** [comment]
should be fixed by 1.5.8. please reopen / comment here if it is not.

**Comment by Countern** [comment]
The error still persists even on 1.5.8 with the following configuration:
```ini
[global]
dxvk = false
renderer = "Vulkan"
```

**Comment by lunarlettuce** [comment]
Please also add `dxvk = false` to [player] and [studio] for now

**Comment by LuaGunsX** [comment]
I had a bit of trouble with above solution, but now it works.
